apiVersion: v1
kind: Service
metadata:
    name: aboladepipelinesjavascriptdocker
spec:
    type: LoadBalancer
    ports:
    - name: old
      port: 80 
    - name: new
      port: 8081
      targetPort: 3000
    selector:
        app: aboladepipelinesjavascriptdocker
